Mvc5StarterKit/Controllers/DashboardController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Mvc5StarterKit.Controllers
{
    public class DashboardController : Controller
    {
        #region Methods
        // GET: DashboardViewer
        public ActionResult DashboardViewer(string id)
        {
            var queryString = Request.QueryString;
            dynamic filters = new System.Dynamic.ExpandoObject();
            foreach (string key in queryString.AllKeys)
            {
                ((IDictionary<string, object>)filters).Add(key, queryString[key]);
            }

            ViewBag.Id = id;
            ViewBag.filters = JsonConvert.SerializeObject(filters);
            return View();
        } 
        #endregion
    }
}

Mvc5StarterKit/Controllers/ReportController.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Mvc5StarterKit.Controllers
{
    public class ReportController : Controller
    {
        #region Methods
        public ActionResult ReportViewer(string id)
        {
            var queryString = Request.QueryString;
            dynamic filters = new System.Dynamic.ExpandoObject();
            foreach (string key in queryString.AllKeys)
            {
                ((IDictionary<string, object>)filters).Add(key, queryString[key]);
            }

            ViewBag.Id = id;
            ViewBag.overridingFilterQueries = JsonConvert.SerializeObject(filters);
            return View();
        }

        public ActionResult ReportParts()
        {
            return View();
        }

        public ActionResult ReportCustomFilterViewer()
        {
            return View();
        }

        public ActionResult AdvancedReportParts()
        {
            return View();
        }
        #endregion
    }
}

Mvc5StarterKit/Views/Shared/Izenda_Layout.cshtml
@using Microsoft.AspNet.Identity
@{

    //Using tenantId, identify location of folder where the css resides for the given tenant and build path to CSS.
    var currentTenant = User.Identity != null ? ((System.Security.Claims.ClaimsIdentity)User.Identity).FindFirstValue("tenantName") : null;
    var izendaCssPath = currentTenant == null ? "" : string.Format("/Content/{0}/izenda-{1}.css", currentTenant.ToString().ToUpper(), currentTenant.ToString().ToLower());

    if (!string.IsNullOrWhiteSpace(izendaCssPath))
    {
        if (!File.Exists(Server.MapPath(izendaCssPath)))
        {
            izendaCssPath = string.Empty;
        }
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @* Apply css based on the users tenant *@
    <link href="~/Scripts/izenda/izenda-ui.css" rel="stylesheet">
    @*Add Custom CSS based on the tenantId and path set in izendaCssPath above *@
    <link href=@izendaCssPath rel="stylesheet">
</head>
<body>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @* #izenda *@
    <script src="~/Scripts/alertify.js"></script>
    @Scripts.Render("~/bundles/izenda")
    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
            $("#reportPartLoader").hide();
            $("#reportPartLoaderText").hide();
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Mvc5StarterKit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Izenda MVC5 DM1 Starterkit</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @* #izenda *@

    @* Apply css based on the users tenant *@
    <link href="~/Scripts/izenda/izenda-ui.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="navbar-header pull-left">
                    <a class="navbar-brand" href="https://www.izenda.com/" target="_blank" rel="noopener noreferrer">
                        <img src="https://3u8npt2xyr3u2fgvai49zopv-wpengine.netdna-ssl.com/wp-content/uploads/2019/05/izenda-logo-white.png" 
                             alt="Site Logo" style="height:18px; width: 100px" />
                    </a>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC5 StarterKit", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        //Izenda Page
                        <li>@Html.ActionLink("Izenda", "Izenda", "Home")</li>

                        @* Settings *@
                        <li>@Html.ActionLink("Settings", "Settings", "Home")</li>

                        @* Reports *@
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Reports
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("New Report", "ReportDesigner", "Home")</li>
                                <li>@Html.ActionLink("Report List", "Reports", "Home")</li>

                                @*For demo, your report id from [IzendaReport] table can be pasted here*@
                                <li>@Html.ActionLink("Report Viewer", "ReportViewer", "Report", new { id = "[your report id]" }, null)</li>

                                @*<li>@Html.ActionLink("Customized Report1 Filters Viewer", "ReportCustomFilterViewer", "Report")</li>*@

                                <li>@Html.ActionLink("Report Parts", "ReportParts", "Report")</li>

                                @*<li>@Html.ActionLink("Advanced Report Parts", "AdvancedReportParts", "Report")</li>*@
                            </ul>
                        </li>

                        @* Dashboards *@
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Dashboards
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("New Dashboard", "DashboardDesigner", "Home")</li>
                                <li>@Html.ActionLink("Dashboard List", "Dashboards", "Home")</li>

                                @*For demo, your dashboard id from [IzendaDashboard] table can be pasted here*@
                                <li>@Html.ActionLink("Dashboard Viewer", "DashboardViewer", "Dashboard", new { id = "[your dashboard id]" }, null)</li>
                            </ul>
                        </li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Izenda Integrated BI Platform</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @* #izenda *@
    <script src="~/Scripts/alertify.js"></script>
    <script src="~/Scripts/izenda/izenda_common.js"></script>
    <script src="~/Scripts/izenda/izenda_locales.js"></script>
    <script src="~/Scripts/izenda/izenda_vendors.js"></script>
    <script src="~/Scripts/izenda/izenda_ui.js"></script>
    <script src="~/Scripts/izenda.integrate.js"></script>
    <script src="~/Scripts/izenda.utils.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
        });
    </script>
</body>
</html>